Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "high_load_2"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

config.vm.network "private_network", ip: "192.168.57.102", :name => 'vboxnet1', :adapter => 2

  # nginx proxy
  config.vm.network "forwarded_port", guest: 9999, host: 9999
  # mysql
  config.vm.network "forwarded_port", guest: 3306, host: 3307

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.ssh.port = 22
    config.ssh.host = '192.168.57.102'
end
