Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "high_load_2"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # nginx proxy
  config.vm.network "forwarded_port", guest: 9999, host: 9999
  # mysql
  config.vm.network "forwarded_port", guest: 3306, host: 3307
  # nginx
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  # apache
  # config.vm.network "forwarded_port", guest: 8081, host: 8081
end
